### ISSUE TITLE
Can't diff two .csv files

### ISSUE THREAD

**Issue by NiklasBr** [fabiospampinato/vscode-diff#3]
This extension seems to ignore all opened .csv files. Is there a setting or something I am missing?

**Comment by fabiospampinato** [comment]
@NiklasBr `.csv` files seem to be ignored because [is-binary-path](https://www.npmjs.com/package/is-binary-path) excludes them [here](https://github.com/sindresorhus/binary-extensions/blob/15014048f519a3aff2ea70670f6a50a2287650b1/binary-extensions.json#L37). Could you perhaps open an issue about this ins [binary-extension](https://github.com/sindresorhus/binary-extensions)'s repo?

**Comment by NiklasBr** [comment]
Thanks, I made a PR: sindresorhus/binary-extensions/pull/21
